### ISSUE TITLE
Better styling for menu

### ISSUE THREAD

**Issue by justKD** [systers/powerup-scenario-builder#11]
## Description
The menu is pretty basic right now. For users, it would probably be better if it was styled to be more attractive, or if it was more isolated and featured at the top of the map space, similar to the app-wide menus for most other apps. (See your browser top menu for an example.)

### Update [Required]
- [ ] Provide mockups for potential options
- [ ] Updating the menu bar styling to be more usable and attractive

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by rossoskull** [comment]
Taking up this issue.
