### ISSUE TITLE
Responsiveness for Menu

### ISSUE THREAD

**Issue by justkd** [systers/powerup-scenario-builder#7]
## Description
The menu at the bottom is just using html to float.

It should be wrapped in a container that uses flex boxes to handle wrapping, so that buttons aren't lost if the window is resized.

### Update [Required]
- [ ] Fix the wrapping for menu bar buttons when the window is sized small.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by rossoskull** [comment]
I would like to work on this issue!
